var CONSTANTS = Object.freeze({
    EPSILON: 1e-60,
    TIMEDELTA: 1,
    TETHER_ELASTICITY: 10,
    TETHER_NUM_NODES: 3,
    PLAYER_MAX_SPEED: 10,
    PLAYER_ACCELERATION: 2,
    DAMPING_COEFFICIENT: 1
});
