var CONSTANTS = Object.freeze({
    MIN_X: 0,
    MIN_Y: 0,
    MAX_X: 1000,
    MAX_Y: 800,
    TIMEDELTA: 1.0/60,
    INPUT_MULTIPLIER: 10,
    EPSILON: 1e-60,
    TETHER_NODE_MASS: 0.01,
    TETHER_NUM_NODES: 100,
    TETHER_NODE_RADIUS: 0.001,
    PLAYER_MAX_SPEED: 10,
    PLAYER_ACCELERATION: 2,
    PLAYER_FRICTION: 0,
    DAMPING_COEFFICIENT: 1
});

module.exports = CONSTANTS;
