var CONSTANTS = Object.freeze({
    LOWER_X: -100.0,
    LOWER_Y: -100.0,
    UPPER_X: 100.0,
    UPPER_Y: 100.0,
    TIMEDELTA: 1.0/60,
    INPUT_MULTIPLIER: 1000,
    EPSILON: 1e-60,
    TETHER_NODE_MASS: 1,
    TETHER_NUM_NODES: 3,
    PLAYER_MAX_SPEED: 10,
    PLAYER_ACCELERATION: 2,
    DAMPING_COEFFICIENT: 1
});

module.exports = CONSTANTS;
